### ISSUE TITLE
ValueError: could not broadcast input array from shape (396) into shape (434)

### ISSUE THREAD

**Issue by isuruthiwa** [saeedkhaki92/CNN-RNN-Yield-Prediction#5]
I get ValueError: could not broadcast input array from shape (396) into shape (434) when running the codes.

This is the stacktrace:

`Traceback (most recent call last):
  File "CNN_RNN_soybean.py", line 703, in <module>
    rmse_tr,rmse_te,train_loss,validation_loss=main_program(X, Index,num_units,num_layers,Max_it, learning_rate, batch_size_tr,le,l)
  File "CNN_RNN_soybean.py", line 520, in main_program
    out_tr = get_sample(dic, A, avg,batch_size_tr, time_steps=5, num_features=316+100+14+4)
  File "CNN_RNN_soybean.py", line 317, in get_sample
    out[i, j, :] = np.concatenate((X[r2, :],np.array([[ym]])),axis=1)
ValueError: could not broadcast input array from shape (396) into shape (434)
`

**Comment by dandelion-zen** [comment]
I am facing the same problem

**Comment by ceavilest** [comment]
Its because the input files have changed, the soil data has been updated.

**Comment by harichandana-yeluri** [comment]
Can any of you share the data files I've emailed them for access by they didn’t responded

**Comment by rahulhanotDTU** [comment]
I am facing the same issue can anybody please help me in this

**Comment by papegu** [comment]
j'ai modifie le nombre de caracteristiques num_features à 396 au niveau de get_sample
et cela a fonctionner

**Comment by BAI233133** [comment]
I have encountered the same problem, has anyone solved it?

**Comment by savankansagra** [comment]
I have solved the error. In the dataset the each soil attribute contain only 6 fields, but in array it considered as 10 fields. Resolved the issue in pull request https://github.com/saeedkhaki92/CNN-RNN-Yield-Prediction/pull/13
